[tool.black]
line-length = 120
target-version = ['py39']  # התאם לגרסת Python שלך, e.g., py39 ל-3.9
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''